@extends('tmp')

@section('title', $pagetitle)

@section('content')

    @if (session('error'))
        <div class="alert alert-{{ Session::get('class') }} p-1" id="success-alert">
            {{ Session::get('error') }}
        </div>
    @endif

    @if ($errors->any())
        <div class="alert alert-danger p-1 border-3">
            <p class="font-weight-bold">There were some problems with your input.</p>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="main-content">
        <div class="page-content">
            <div class="container-fluid">

                <!-- Page Title -->
                <div class="row">
                    <div class="col-12">
                        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                            <h4 class="mb-sm-0 font-size-18">Vendor Umrah Report</h4>
                            <a href="{{ url('/VendorReports') }}" class="btn btn-info btn-sm">
                                <i class="mdi mdi-format-list-bulleted"></i> View Generated Reports
                            </a>
                        </div>
                    </div>
                </div>

                <!-- Search Form -->
                <div class="card shadow-sm">
                    <div class="card-body">

                        <form action="{{ url('/VendorReportPreview') }}" method="post" id="vendorReportForm">
                            {{ csrf_field() }}

                            <?php $users = DB::table('user')->get(); ?>

                            @include('components.start_end_date')

                            <!-- Generated By -->
                            <div class="col-md-4 mt-2">
                                <div class="mb-3">
                                    <label>Report Generated By</label>
                                    <select name="GeneratedBy" id="GeneratedBy" class="form-select">
                                        <option value="">Select User</option>
                                        @foreach ($users as $u)
                                            <option value="{{ $u->UserID }}">{{ $u->FullName }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <!-- Item -->
                            <div class="col-md-4 mt-2">
                                <div class="mb-3">
                                    <label>Item *</label>
                                    <select name="ItemID" id="ItemID" class="form-select">
                                        <option value="">Any</option>
                                        @foreach ($item as $i)
                                            <option value="{{ $i->ItemID }}">{{ $i->ItemName }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <!-- Report Type -->
                            <div class="col-md-4 mt-2">
                                <div class="mb-3">
                                    <label>Report Type *</label>
                                    <select name="Type" id="Type" class="form-select">
                                        <option value="Date">Invoice Date</option>
                                        <option value="DepartureDate" selected>Departure Date</option>
                                    </select>
                                </div>
                            </div>
                    </div>

                    <div class="card-footer bg-light">
                        <button type="submit" class="btn btn-success w-lg float-right">Preview Report</button>
                    </div>

                    </form>
                </div>

            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script>
        $(document).ready(function() {
            $('#StartDate').on('change', function() {
                var startDate = $(this).val();
                var endDate = $('#EndDate').val();

                if (!endDate || new Date(endDate) < new Date(startDate)) {
                    $('#EndDate').val(startDate);
                }

                $('#EndDate').attr('min', startDate);
            });
        });
    </script>

@endsection
