@extends('template.tmp')

@section('title', 'Vendor Reports History')

@section('content')
    <div class="main-content">
        <div class="page-content">
            <div class="container-fluid">

                <div class="row">
                    <div class="col-12">
                        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                            <h4 class="mb-sm-0 font-size-18">Vendor Reports History</h4>
                            <div class="col d-flex justify-content-end">
                                <a href="{{ url('/VendorUmrahReport') }}" class="btn btn-success">
                                    <i class="mdi mdi-plus"></i> Generate New Report
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Success/Error Messages -->
                @if (session('error'))
                    <div class="alert alert-{{ session('class') ?? 'danger' }} alert-dismissible fade show" role="alert">
                        {{ session('error') }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                    </div>
                @endif

                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="vendor-reports-table" class="table table-sm table-hover table-bordered w-100">
                                <thead class="table-light">
                                    <tr>
                                        <th>#</th>
                                        <th>Generated By</th>
                                        <th>Departure Range</th>
                                        <th>Generated On</th>
                                        <th width="150">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse($reports as $index => $report)
                                        <tr>
                                            <td>{{ $report->id }}</td>
                                            <td>
                                                <span class="badge bg-primary">{{ $report->generated_by_name }}</span>
                                            </td>
                                            <td>
                                                {{ \Carbon\Carbon::parse($report->departure_start)->format('d-m-Y') }}
                                                <strong>to</strong>
                                                {{ \Carbon\Carbon::parse($report->departure_end)->format('d-m-Y') }}
                                            </td>
                                            <td>{{ \Carbon\Carbon::parse($report->generated_date)->format('d-m-Y') }}</td>
                                            <td>
                                                <a href="{{ url('/VendorReportView/' . $report->id) }}"
                                                    class="btn btn-sm btn-primary" title="View Report">
                                                    <i class="mdi mdi-eye"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    @empty
                                        <tr>
                                            <td colspan="7" class="text-center text-muted py-4">
                                                <i class="mdi mdi-file-document-outline fs-1"></i><br>
                                                No vendor reports generated yet.
                                            </td>
                                        </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <!-- DataTable + Scripts -->
    <script src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.7/js/dataTables.bootstrap5.min.js"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/dataTables.bootstrap5.min.css">

    <script>
        $(document).ready(function() {
            $('#vendor-reports-table').DataTable({
                ordering: true,
                order: [
                    [0, 'desc']
                ], // Latest first
                pageLength: 25,
                columnDefs: [{
                        orderable: false,
                        targets: 6
                    } // Disable sorting on Action column
                ],
                language: {
                    emptyTable: "No vendor reports found",
                    zeroRecords: "No matching reports found"
                }
            });
        });
    </script>
@endsection
