@extends('template.tmp')

@section('title', 'Vendor Umrah Report')

@section('content')

    <div class="main-content">
        <div class="page-content">
            <div class="container-fluid">

                <!-- Page Title + Report Info Banner -->
                <div class="row">
                    <div class="col-12">
                        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                            <div>
                                <h4 class="mb-sm-0 font-size-18">Vendor Umrah Report</h4>

                                @if (isset($report))
                                    <div class="mt-2">
                                        <small class="text-muted">
                                            <strong>Report ID:</strong> #{{ $report->id }}
                                            &nbsp; | &nbsp;
                                            <strong>Generated By:</strong>
                                            {{ $report->generated_by_name ?? 'Unknown User' }}
                                            &nbsp; | &nbsp;
                                            <strong>Date:</strong>
                                            {{ \Carbon\Carbon::parse($report->generated_date)->format('d-m-Y') }}
                                            &nbsp; | &nbsp;
                                            <strong>Departure Range:</strong>
                                            {{ \Carbon\Carbon::parse($report->departure_start)->format('d-m-Y') }}
                                            to
                                            {{ \Carbon\Carbon::parse($report->departure_end)->format('d-m-Y') }}
                                        </small>
                                    </div>
                                @endif
                            </div>

                            <!-- Generate & Lock Button (Only on Preview) -->
                            @if (!isset($report) && !empty($report_data) && count($report_data) > 0)
                                <div class="row mt-3">
                                    <div class="col-12 text-end">
                                        <form action="{{ url('/VendorReportLock') }}" method="post" class="d-inline">
                                            {{ csrf_field() }}
                                            <input type="hidden" name="StartDate" value="{{ request()->StartDate }}">
                                            <input type="hidden" name="EndDate" value="{{ request()->EndDate }}">
                                            <input type="hidden" name="Type" value="{{ request()->Type }}">
                                            <input type="hidden" name="GeneratedBy"
                                                value="{{ request()->GeneratedBy }}">
                                            <!-- Fallback to logged in user or default 1 -->
                                            <input type="hidden" name="ItemID" value="{{ request()->ItemID }}">
                                            <input type="hidden" name="UserID" value="{{ request()->UserID }}">

                                            <button type="submit" class="btn btn-danger btn-lg"
                                                onclick="return confirm('WARNING: This will LOCK these records FOREVER!\n\nAre you sure you want to generate and lock this report?')">
                                                <i class="mdi mdi-lock"></i> Generate & Lock Report
                                            </button>
                                        </form>
                                        <a href="{{ url('/VendorUmrahReport') }}" class="btn btn-secondary btn-lg ms-2">
                                            <i class="mdi mdi-arrow-left"></i> Back to Search
                                        </a>
                                    </div>
                                </div>
                            @endif

                            <div>
                                @if (isset($report))
                                    <a href="{{ url('/VendorReportPDF/' . $report->id) }}" target="_blank"
                                        class="btn btn-success btn-sm">
                                        <i class="mdi mdi-download"></i> Full Report PDF
                                    </a>
                                    <a href="{{ url('/VendorReports') }}" class="btn btn-secondary btn-sm">
                                        <i class="mdi mdi-arrow-left"></i> Back to List
                                    </a>
                                @else
                                    <a href="{{ url('/VendorReports') }}" class="btn btn-primary btn-sm">
                                        <i class="mdi mdi-format-list-bulleted"></i> View All Reports
                                    </a>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Success Message -->
                @if (session('success'))
                    <div class="alert alert-success alert-dismissible fade show mt-3" role="alert">
                        <i class="mdi mdi-check-all me-2"></i>
                        {!! session('success') !!}
                        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                    </div>
                @endif

                <!-- Report Content -->
                @if (!empty($report_data) && count($report_data) > 0)

                    @foreach ($report_data as $data)
                        @php
                            $sup = $data['supplier'];
                            $records = $data['records'];

                            $totalUmrahFare = $totalFare = $totalService = $totalVAT = $totalInvoice = $totalPaid = 0;
                        @endphp

                        <div class="card shadow-sm mt-4">
                            <!-- Supplier Header with Export Dropdown -->
                            <div class="card-body border-primary border-top border-3 rounded-top">
                                <div class="row align-items-center">
                                    <div class="col-md-6">
                                        <h3 class="mb-0">
                                            <i class="mdi mdi-office-building"></i> {{ $sup->SupplierName }}
                                        </h3>
                                    </div>
                                    <div class="col-md-6 text-end">
                                        <div class="dropdown d-inline-block">
                                            <button class="btn btn-danger dropdown-toggle waves-effect waves-light"
                                                type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                                <i class="mdi mdi-export"></i> Export Options
                                            </button>
                                            <ul class="dropdown-menu dropdown-menu-end">
                                                <li>
                                                    <a class="dropdown-item"
                                                        href="{{ url('/VendorReportSupplierPDF') }}/{{ isset($report) ? $report->id : 'new' }}/{{ $sup->SupplierID }}"
                                                        target="_blank">
                                                        <i class="mdi mdi-file-pdf-outline"></i> Export PDF
                                                    </a>
                                                </li>
                                                <li>
                                                    <a class="dropdown-item"
                                                        href="{{ url('/VendorReportSupplierVendorPDF') }}/{{ isset($report) ? $report->id : 'new' }}/{{ $sup->SupplierID }}"
                                                        target="_blank">
                                                        <i class="mdi mdi-file-pdf-outline"></i> For Vendor
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <!-- Table Body -->
                            <div class="card-body pt-3">
                                @if ($records->isNotEmpty())
                                    <div class="table-responsive">
                                        <table class="table table-sm table-bordered table-striped table-hover align-middle">
                                            <thead class="table-primary">
                                                <tr>
                                                    <th>S.No</th>
                                                    <th>INV#</th>
                                                    <th>Salesman</th>
                                                    <th>Pax Name</th>
                                                    <th>Contact</th>
                                                    <th>Passport</th>
                                                    <th>Nationality</th>
                                                    <th>Pick Point</th>
                                                    <th>Room</th>
                                                    <th>Visa</th>
                                                    <th>Departure</th>
                                                    <th>Umrah Fare</th>
                                                    <th>Fare</th>
                                                    <th>Service</th>
                                                    <th>VAT</th>
                                                    <th>Total</th>
                                                    <th>Paid</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach ($records as $k => $r)
                                                    @php
                                                        $totalUmrahFare += $r->UmrahFare;
                                                        $totalFare += $r->Fare;
                                                        $totalService += $r->Service;
                                                        $totalVAT += $r->Taxable;
                                                        $totalInvoice += $r->Total;
                                                        $totalPaid += $r->Paid;
                                                    @endphp
                                                    <tr>
                                                        <td>{{ $k + 1 }}</td>
                                                        <td>
                                                            {{-- <a href="{{ url('/UmrahPDF/' . $r->InvoiceMasterID) }}"
                                                                target="_blank" class="text-decoration-underline">
                                                                {{ $r->InvoiceMasterID }}
                                                            </a> --}}
                                                            {{ $r->InvoiceMasterID }}
                                                        </td>
                                                        <td>{{ $r->SalemanName }}</td>
                                                        <td><strong>{{ $r->PaxName }}</strong></td>
                                                        <td>{{ $r->Contact }}</td>
                                                        <td>{{ $r->Passport }}</td>
                                                        <td>{{ $r->Nationality }}</td>
                                                        <td>{{ $r->PickPoint }}</td>
                                                        <td>{{ $r->RoomType }}</td>
                                                        <td>{{ $r->VisaType }}</td>
                                                        <td>{{ \Carbon\Carbon::parse($r->DepartureDate)->format('d-m-Y') }}
                                                        </td>
                                                        <td class="text-end">{{ number_format($r->UmrahFare, 2) }}</td>
                                                        <td class="text-end">{{ number_format($r->Fare, 2) }}</td>
                                                        <td class="text-end">{{ number_format($r->Service, 2) }}</td>
                                                        <td class="text-end">{{ number_format($r->Taxable, 2) }}</td>
                                                        <td class="text-end fw-bold">{{ number_format($r->Total, 2) }}</td>
                                                        <td
                                                            class="text-end {{ $r->Paid < $r->Total ? 'text-danger' : 'text-success' }}">
                                                            {{ number_format($r->Paid, 2) }}
                                                        </td>
                                                    </tr>
                                                @endforeach

                                                <!-- Grand Total Row -->
                                                <tr class="table-info fw-bold">
                                                    <td colspan="11" class="text-center">TOTAL ({{ $records->count() }}
                                                        Records)</td>
                                                    <td class="text-end">{{ number_format($totalUmrahFare, 2) }}</td>
                                                    <td class="text-end">{{ number_format($totalFare, 2) }}</td>
                                                    <td class="text-end">{{ number_format($totalService, 2) }}</td>
                                                    <td class="text-end">{{ number_format($totalVAT, 2) }}</td>
                                                    <td class="text-end">{{ number_format($totalInvoice, 2) }}</td>
                                                    <td class="text-end">{{ number_format($totalPaid, 2) }}</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                @else
                                    <div class="text-center py-5 text-muted">
                                        <i class="mdi mdi-information-outline fs-1"></i>
                                        <p>No records found for this supplier.</p>
                                    </div>
                                @endif
                            </div>
                        </div>
                    @endforeach
                @else
                    <div class="card mt-4">
                        <div class="card-body text-center py-5">
                            <i class="mdi mdi-file-document-outline text-muted fs-1"></i>
                            <h5 class="mt-3 text-muted">No Records Found</h5>
                            <p class="text-muted">
                                @if (isset($report))
                                    This report (#{{ $report->id }}) contains no records.
                                @else
                                    No vendor records found for the selected criteria.
                                @endif
                            </p>
                        </div>
                    </div>
                @endif

            </div>
        </div>
    </div>

@endsection
