<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Vendor Report #{{ $report->id }}</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 11px; margin: 20px; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #333; padding-bottom: 10px; }
        .company { font-size: 16px; font-weight: bold; }
        table { width: 100%; border-collapse: collapse; margin: 15px 0; }
        th, td { border: 1px solid #333; padding: 6px; text-align: left; }
        th { background-color: #f0f0f0; font-weight: bold; }
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .total-row { background-color: #e6f3ff; font-weight: bold; }
        h3 { color: #2c3e50; margin-top: 30px; border-bottom: 1px solid #ddd; padding-bottom: 5px; }
        .footer { margin-top: 50px; text-align: center; color: #666; font-size: 10px; }
    </style>
</head>
<body>

<div class="header">
    <div class="company">{{ $company->CompanyName ?? 'Your Company' }}</div>
    <div>Vendor Umrah Report</div>
    <div style="margin-top: 10px; font-size: 12px;">
        <strong>Report ID:</strong> #{{ $report->id }} 
        | <strong>Generated By:</strong> {{ $report->generated_by_name ?? 'N/A' }}
        | <strong>Date:</strong> {{ date('d-m-Y', strtotime($report->generated_date)) }}<br>
        <strong>Departure Range:</strong> 
        {{ date('d-m-Y', strtotime($report->departure_start)) }} to {{ date('d-m-Y', strtotime($report->departure_end)) }}
    </div>
</div>

@forelse($report_data as $data)
    @php
        $sup = $data['supplier'];
        $records = $data['records'];
        $totals = ['umrah'=>0, 'fare'=>0, 'service'=>0, 'vat'=>0, 'total'=>0, 'paid'=>0];
    @endphp

    <h3>{{ $sup->SupplierName }}</h3>

    <table>
        <thead>
            <tr>
                <th width="5%">S.No</th>
                <th width="8%">INV#</th>
                <th>Salesman</th>
                <th>Pax Name</th>
                <th>Contact</th>
                <th>Passport</th>
                <th>Departure</th>
                <th>Umrah Fare</th>
                <th>Fare</th>
                <th>Service</th>
                <th>VAT</th>
                <th>Total</th>
                <th>Paid</th>
            </tr>
        </thead>
        <tbody>
            @foreach($records as $k => $r)
                @php
                    $totals['umrah'] += $r->UmrahFare;
                    $totals['fare'] += $r->Fare;
                    $totals['service'] += $r->Service;
                    $totals['vat'] += $r->Taxable;
                    $totals['total'] += $r->Total;
                    $totals['paid'] += $r->Paid;
                @endphp
                <tr>
                    <td class="text-center">{{ $k + 1 }}</td>
                    <td>{{ $r->InvoiceMasterID }}</td>
                    <td>{{ $r->SalemanName }}</td>
                    <td>{{ $r->PaxName }}</td>
                    <td>{{ $r->Contact }}</td>
                    <td>{{ $r->Passport }}</td>
                    <td>{{ date('d-m-Y', strtotime($r->DepartureDate)) }}</td>
                    <td class="text-right">{{ number_format($r->UmrahFare, 2) }}</td>
                    <td class="text-right">{{ number_format($r->Fare, 2) }}</td>
                    <td class="text-right">{{ number_format($r->Service, 2) }}</td>
                    <td class="text-right">{{ number_format($r->Taxable, 2) }}</td>
                    <td class="text-right"><strong>{{ number_format($r->Total, 2) }}</strong></td>
                    <td class="text-right">{{ number_format($r->Paid, 2) }}</td>
                </tr>
            @endforeach
            <tr class="total-row">
                <td colspan="7" class="text-center"><strong>TOTAL ({{ $records->count() }} Records)</strong></td>
                <td class="text-right"><strong>{{ number_format($totals['umrah'], 2) }}</strong></td>
                <td class="text-right"><strong>{{ number_format($totals['fare'], 2) }}</strong></td>
                <td class="text-right"><strong>{{ number_format($totals['service'], 2) }}</strong></td>
                <td class="text-right"><strong>{{ number_format($totals['vat'], 2) }}</strong></td>
                <td class="text-right"><strong>{{ number_format($totals['total'], 2) }}</strong></td>
                <td class="text-right"><strong>{{ number_format($totals['paid'], 2) }}</strong></td>
            </tr>
        </tbody>
    </table>
@empty
    <p class="text-center">No records found in this report.</p>
@endforelse

<div class="footer">
    Report generated on: {{ date('d-m-Y H:i:s') }} 
    | Powered by Your System
</div>

</body>
</html>